version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ajv
    versions:
    - ">= 8.a, < 9"
  - dependency-name: cucumber
    versions:
    - "> 1.3.2"
  - dependency-name: y18n
    versions:
    - "> 4.0.0, < 4.1"
  - dependency-name: rollup
    versions:
    - 2.42.4
    - 2.43.0
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: ajv
    versions:
    - 7.2.4
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
    - 8.3.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
    - 10.5.4
  - dependency-name: npm-user-validate
    versions:
    - 1.0.1
  - dependency-name: deep-equal
    versions:
    - 2.0.5
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: cross-spawn
    versions:
    - 7.0.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
