# GH_TOKEN and NPM_TOKEN are expected to be set
# in https://travis-ci.org/apiaryio/gavel.js/settings
language: "node_js"
node_js:
  - "6"
  - "8"
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - "npm -g install npm@6"
after_success:
  - "npm run coveralls || true"
  - "npm run semantic-release || true"
