language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
notifications:
  email:
    recipients:
      - adam@apiary.io
    on_success: change
    on_failure: always
after_success:
  - ./scripts/coveralls
before_install:
  - npm install -g npm@1.4.28
