sudo: false
language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
env:
  global:
    # GH_TOKEN and NPM_TOKEN encrypted by 'travis encrypt' utility
    - secure: "aLqvApCqqaLWbbNhuCdDL02g9j5O1R00rTBo3h7Lb0LnS302Gl4XIFdjcehwOSFWJkd3Rv25A6weiOqEKo9zgGknHjY73ao1BxBaPFFhwMRY4qEVZ3oqhpf5oBuO66tf8l3cHhNkrhXgDtu9J+XU/FetM7PfGyCqhxzLdVMPcXI="
cache:
  directories:
    - "node_modules"
before_install:
  - "npm -g install npm@latest"
  - "curl -Lo travis_after_all.py https://raw.githubusercontent.com/dmakhno/travis_after_all/master/travis_after_all.py"
before_script:  # https://github.com/cucumber/cucumber-js/issues/602
  - "if [[ $TRAVIS_NODE_VERSION = '0.10' ]]; then npm install cucumber@1.0.0; fi"
after_success:  # travis_after_all.py is needed due to travis-ci/travis-ci#1548 & travis-ci/travis-ci#929
  - "npm run coveralls"
  - "python travis_after_all.py"
  - "export $(cat .to_export_back)"
  - "npm run semantic-release || true"
