# GH_TOKEN and NPM_TOKEN are expected to be set
# in https://travis-ci.org/apiaryio/gavel.js/settings
language: 'node_js'
node_js:
  - '8'
  - '10'
  - '12'
cache:
  directories:
    - 'node_modules'
before_install:
  - 'npm -g install npm@6'
install:
  - 'npm install --no-save'
script:
  - 'npm run ci:lint'
  - 'npm run ci:test'
after_success:
  - 'npm run ci:release'
