environment:
  nodejs_version: '10'
cache:
  - 'node_modules'
install:
  - ps: Install-Product node 10
  - 'npm -g install npm@6'
  - "set PATH=%APPDATA%\\npm;%PATH%"
  - 'npm install'
build: off
test_script:
  - 'node --version'
  - 'npm --version'
  - 'npm run build'
  - 'npm test'
