// Generated by CoffeeScript 1.6.3
var HitStructure, packageJson;

packageJson = require('../../package.json');

HitStructure = HitStructure = (function() {
  function HitStructure() {
    this.schemaVersion = 2;
    this.validatorVersion = "" + packageJson.version;
    this.request = {
      validationResults: {
        headers: null,
        body: null
      },
      expected: {
        userSchemas: [],
        headers: {},
        body: '',
        schema: {
          headers: '',
          body: ''
        }
      },
      real: {
        headers: {},
        body: ''
      }
    };
    this.response = {
      validationResults: {
        headers: null,
        body: null,
        statusCode: null
      },
      expected: {
        userSchemas: [],
        headers: {},
        body: '',
        schema: {
          headers: '',
          body: ''
        },
        statusCode: ''
      },
      real: {
        headers: {},
        body: '',
        statusCode: ''
      }
    };
  }

  return HitStructure;

})();
