// Generated by CoffeeScript 1.6.3
var ExpectedHttpRequest, HttpRequest;

require('./mixins');

HttpRequest = HttpRequest = (function() {
  HttpRequest.actAsValidatable();

  function HttpRequest(_arg) {
    this.method = _arg.method, this.url = _arg.url, this.headers = _arg.headers, this.body = _arg.body, this.expected = _arg.expected;
  }

  return HttpRequest;

})();

ExpectedHttpRequest = ExpectedHttpRequest = (function() {
  function ExpectedHttpRequest(_arg) {
    this.method = _arg.method, this.url = _arg.url, this.headers = _arg.headers, this.body = _arg.body, this.headersSchema = _arg.headersSchema, this.bodySchema = _arg.bodySchema;
  }

  return ExpectedHttpRequest;

})();

module.exports = {
  HttpRequest: HttpRequest,
  ExpectedHttpRequest: ExpectedHttpRequest
};
