// Generated by CoffeeScript 1.6.3
var HttpMessage;

require('./mixins');

HttpMessage = HttpMessage = (function() {
  HttpMessage.actAsValidatableMessage();

  function HttpMessage(_arg) {
    this.httpRequest = _arg.httpRequest, this.httpResponse = _arg.httpResponse;
  }

  return HttpMessage;

})();

module.exports = {
  HttpMessage: HttpMessage
};
