// Generated by CoffeeScript 1.6.3
var DataNotJsonParcableError, DataNotJsonParsableError, DataNotStringError, MalformedDataError, MalformedSchemaError, NotEnoughDataError, NotValidatableError, SchemaNotJsonParsableError, UnknownValidatorError, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MalformedDataError = MalformedDataError = (function(_super) {
  __extends(MalformedDataError, _super);

  function MalformedDataError() {
    _ref = MalformedDataError.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return MalformedDataError;

})(Error);

DataNotJsonParsableError = DataNotJsonParsableError = (function(_super) {
  __extends(DataNotJsonParsableError, _super);

  function DataNotJsonParsableError() {
    _ref1 = DataNotJsonParsableError.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  return DataNotJsonParsableError;

})(MalformedDataError);

DataNotStringError = DataNotStringError = (function(_super) {
  __extends(DataNotStringError, _super);

  function DataNotStringError() {
    _ref2 = DataNotStringError.__super__.constructor.apply(this, arguments);
    return _ref2;
  }

  return DataNotStringError;

})(MalformedDataError);

MalformedSchemaError = MalformedSchemaError = (function(_super) {
  __extends(MalformedSchemaError, _super);

  function MalformedSchemaError() {
    _ref3 = MalformedSchemaError.__super__.constructor.apply(this, arguments);
    return _ref3;
  }

  return MalformedSchemaError;

})(Error);

SchemaNotJsonParsableError = DataNotJsonParcableError = (function(_super) {
  __extends(DataNotJsonParcableError, _super);

  function DataNotJsonParcableError() {
    _ref4 = DataNotJsonParcableError.__super__.constructor.apply(this, arguments);
    return _ref4;
  }

  return DataNotJsonParcableError;

})(MalformedSchemaError);

UnknownValidatorError = UnknownValidatorError = (function(_super) {
  __extends(UnknownValidatorError, _super);

  function UnknownValidatorError() {
    _ref5 = UnknownValidatorError.__super__.constructor.apply(this, arguments);
    return _ref5;
  }

  return UnknownValidatorError;

})(Error);

NotValidatableError = NotValidatableError = (function(_super) {
  __extends(NotValidatableError, _super);

  function NotValidatableError() {
    _ref6 = NotValidatableError.__super__.constructor.apply(this, arguments);
    return _ref6;
  }

  return NotValidatableError;

})(Error);

NotEnoughDataError = NotEnoughDataError = (function(_super) {
  __extends(NotEnoughDataError, _super);

  function NotEnoughDataError() {
    _ref7 = NotEnoughDataError.__super__.constructor.apply(this, arguments);
    return _ref7;
  }

  return NotEnoughDataError;

})(Error);

module.exports = {
  DataNotJsonParsableError: DataNotJsonParsableError,
  SchemaNotJsonParsableError: SchemaNotJsonParsableError,
  MalformedSchemaError: MalformedSchemaError,
  MalformedDataError: MalformedDataError,
  UnknownValidatorError: UnknownValidatorError,
  DataNotStringError: DataNotStringError,
  NotValidatableError: NotValidatableError,
  NotEnoughDataError: NotEnoughDataError
};
