// Generated by CoffeeScript 1.6.3
var JsonValidator, amanda, data, fixtures, schema, validator;

amanda = require('amanda');

fixtures = require('../test/fixtures');

JsonValidator = require('./validators/json-validator').JsonValidator;

data = {};

schema = JSON.parse(JSON.stringify(JSON.parse(fixtures.sampleJsonSchemaNonStrict)));

validator = new JsonValidator({
  data: JSON.parse(fixtures.sampleJsonArrayItemMissing),
  schema: JSON.parse(fixtures.sampleJsonSchemaNonStrict)
});

console.error(validator.validate());
