// Generated by CoffeeScript 1.6.3
var extendable;

extendable = {
  extend: function(obj, self) {
    var key, value, _ref;
    for (key in obj) {
      value = obj[key];
      if (key !== 'extended' && key !== 'included') {
        self[key] = value;
      }
    }
    if ((_ref = obj.extended) != null) {
      _ref.apply(self);
    }
    return this;
  },
  include: function(obj, self) {
    var key, value, _ref;
    for (key in obj) {
      value = obj[key];
      if (key !== 'extended' && key !== 'included') {
        self.prototype[key] = value;
      }
    }
    if ((_ref = obj.included) != null) {
      _ref.apply(self);
    }
    return this;
  }
};

module.exports = {
  extendable: extendable
};
