#!/bin/sh
git submodule init
git submodule update
if [ -d "src/" ]; then
	rm -fr lib/
	node_modules/.bin/coffee -b -c -o lib/ src/
	#mkdir lib
	#cp -a -R src/* lib/
fi
cp test/cucumber/features/node_js/Readme.md ./
cp src/meta-schema-v3.json lib/meta-schema-v3.json
cp src/meta-schema-v4.json lib/meta-schema-v4.json

