#!/bin/sh
# Usage:
# ./scripts/cov [reporter]
#
# Example:
# ./scripts/cov html-cov > cov.html


COV=./node_modules/.bin/coffeeCoverage
MOCHA=./node_modules/.bin/mocha
REPORTER=$1


# Cleanup & preparation
rm -rf ./src-cov ./lcov ./cov.info
mkdir ./src-cov ./lcov

# Creating directory with instrumented JS code
$COV --exclude=node_modules,.git,test --path=relative . ./src-cov 1>&2
cp ./package.json ./src-cov
cp -r ./test ./src-cov/test

# Testing
$MOCHA ./src-cov/test/unit/**/*-test.coffee --reporter="$REPORTER"

# Output & cleanup
rm -rf ./src-cov
